// Content of the infographic. Edit here; app.js only renders.
// Dates are 'YYYY-MM' (day optional) and drive the timeline axis.

export const ERAS = [
  { id: 1, name: 'Los cimientos', years: '2017 – 2019', from: '2017-01', to: '2020-01',
    thesis: 'Una arquitectura que se paraleliza en GPU cambia qué se puede entrenar.' },
  { id: 2, name: 'La apuesta por la escala', years: '2020 – 2022', from: '2020-01', to: '2022-11',
    thesis: 'Más datos, más parámetros, más cómputo: el error baja de forma predecible.' },
  { id: 3, name: 'La explosión', years: 'nov 2022 – 2023', from: '2022-11', to: '2024-01',
    thesis: 'Una interfaz de chat convierte una tecnología de laboratorio en producto masivo. Todos entran a la carrera.' },
  { id: 4, name: 'Ver, oír… y pensar', years: '2024', from: '2024-01', to: '2025-01',
    thesis: 'Los modelos dejan de ser solo texto, y aparece una nueva palanca: gastar cómputo al responder.' },
  { id: 5, name: 'El razonamiento se abre', years: '2025', from: '2025-01', to: '2026-01',
    thesis: 'Un laboratorio chino publica un razonador abierto y barato. La ventaja de la frontera se mide ahora en meses.' },
  { id: 6, name: 'De responder a ejecutar', years: '2026', from: '2026-01', to: '2026-12',
    thesis: 'El foco pasa al trabajo autónomo: tareas de horas, programación y uso del computador.' },
];

export const TAGS = {
  open: 'abierto',
  closed: 'cerrado',
  reasoning: 'razonador',
  multimodal: 'multimodal',
};

export const EVENTS = [
  { era: 1, date: '2017-06', label: 'jun 2017', key: true, title: 'Attention Is All You Need', who: 'Vaswani et al. · Google',
    text: 'Elimina la recurrencia: solo atención. Nace el Transformer, base de todo lo que sigue.',
    why: 'Las redes recurrentes procesaban palabra por palabra. La atención mira toda la secuencia a la vez, así que el entrenamiento se reparte en miles de núcleos de GPU. Sin esa paralelización, la escala de los años siguientes habría sido inviable.',
    tags: [], src: 'https://arxiv.org/abs/1706.03762' },
  { era: 1, date: '2018-06', label: 'jun 2018', title: 'GPT-1', who: 'OpenAI',
    text: 'Pre-entrenar con texto sin etiquetar y luego ajustar: el patrón generative pre-trained.',
    why: 'Demostró que un modelo que solo aprende a predecir la siguiente palabra adquiere conocimiento reutilizable para muchas tareas. La «P» de GPT viene de aquí.',
    tags: [], src: 'https://openai.com/index/language-unsupervised/' },
  { era: 1, date: '2018-10', label: 'oct 2018', title: 'BERT', who: 'Google',
    text: 'Transformer bidireccional; domina la comprensión de texto y llega al buscador de Google en 2019.',
    why: 'Mientras GPT generaba, BERT entendía: leía en ambas direcciones y se volvió el estándar para clasificar, buscar y extraer información durante años.',
    tags: ['open'], src: 'https://arxiv.org/abs/1810.04805' },
  { era: 1, date: '2019-02', label: 'feb 2019', title: 'GPT-2', who: 'OpenAI · liberado completo en nov 2019',
    text: '1.500 M de parámetros. OpenAI retiene la versión completa por riesgo de mal uso.',
    why: 'Primer debate público sobre si un modelo de lenguaje era «demasiado peligroso para publicarse». La liberación escalonada inauguró la discusión sobre despliegue responsable.',
    tags: ['open'], src: 'https://openai.com/index/better-language-models/' },

  { era: 2, date: '2020-01', label: 'ene 2020', title: 'Leyes de escalamiento', who: 'Kaplan et al. · OpenAI',
    text: 'La pérdida cae como ley de potencias con el tamaño del modelo, los datos y el cómputo.',
    why: 'Convirtió el progreso en algo predecible: si sabes cuánto cómputo pones, puedes estimar cuánto mejorará el modelo. Eso justificó inversiones de miles de millones.',
    tags: [], src: 'https://arxiv.org/abs/2001.08361' },
  { era: 2, date: '2020-05', label: 'may 2020', key: true, title: 'GPT-3', who: 'OpenAI',
    text: '175.000 M de parámetros. Aprende tareas con unos pocos ejemplos en el prompt (few-shot), sin reentrenar.',
    why: 'El aprendizaje «en contexto» apareció sin que nadie lo programara: bastaba con mostrar ejemplos en el texto. Nació la ingeniería de prompts.',
    tags: ['closed'], src: 'https://arxiv.org/abs/2005.14165' },
  { era: 2, date: '2021-01', label: '2021', title: 'Nace Anthropic', who: 'San Francisco',
    text: 'Ex-integrantes de OpenAI, con Dario y Daniela Amodei, fundan un laboratorio centrado en seguridad.',
    why: 'Primera gran escisión del sector: un grupo que creía en la escala, pero con prioridad en la seguridad y la interpretabilidad. De ahí saldría Claude.',
    tags: [], src: 'https://www.anthropic.com/company' },
  { era: 2, date: '2021-03', label: 'mar 2021', title: '«Stochastic Parrots»', who: 'Bender, Gebru, McMillan-Major, Mitchell',
    text: 'Advierte sobre forma sin significado, sesgos heredados y costo ambiental. Nombra al loro estocástico.',
    why: 'Puso nombre a la crítica más influyente contra los LLM. Ver la sección 04.',
    tags: [], src: 'https://doi.org/10.1145/3442188.3445922' },
  { era: 2, date: '2022-03', label: 'mar 2022', title: 'InstructGPT · Chinchilla', who: 'OpenAI · DeepMind',
    text: 'RLHF enseña a seguir instrucciones; Chinchilla muestra que faltaban datos, no parámetros.',
    why: 'RLHF (aprendizaje por refuerzo con retroalimentación humana) es lo que convirtió un predictor de texto en un asistente útil. Chinchilla corrigió la receta: para el mismo cómputo, modelos más pequeños con muchos más datos.',
    tags: [], src: 'https://arxiv.org/abs/2203.02155' },

  { era: 3, date: '2022-11-30', label: '30 nov 2022', key: true, title: 'ChatGPT', who: 'OpenAI',
    text: 'Un chat sobre GPT-3.5 ajustado con RLHF. ~100 M de usuarios en dos meses.',
    why: 'La tecnología no era nueva; la interfaz sí. Una caja de chat gratuita llevó los LLM al público general y desató la carrera de toda la industria.',
    tags: ['closed'], src: 'https://openai.com/index/chatgpt/' },
  { era: 3, date: '2023-02', label: 'feb 2023', title: 'LLaMA', who: 'Meta',
    text: 'Meta lo comparte con investigadores; los pesos se filtran en días y arranca la comunidad abierta.',
    why: 'Por primera vez cualquiera con una GPU podía ajustar un modelo competitivo. Surgieron Alpaca, Vicuna y miles de variantes en semanas.',
    tags: ['open'], src: 'https://arxiv.org/abs/2302.13971' },
  { era: 3, date: '2023-03-14', label: '14 mar 2023', title: 'GPT-4 y Claude', who: 'OpenAI · Anthropic',
    text: 'El mismo día: GPT-4 acepta imágenes como entrada; Anthropic lanza su primer Claude.',
    why: 'GPT-4 marcó la frontera durante más de un año y fue el primer gran modelo comercial multimodal. Claude abrió la competencia directa con OpenAI.',
    tags: ['closed', 'multimodal'], src: 'https://arxiv.org/abs/2303.08774' },
  { era: 3, date: '2023-07', label: 'jul 2023', title: 'Llama 2', who: 'Meta',
    text: 'Pesos abiertos con licencia de uso comercial: las empresas pueden construir encima.',
    why: 'Legalizó lo que LLaMA había hecho por accidente: el modelo abierto pasó a ser una estrategia corporativa.',
    tags: ['open'], src: 'https://arxiv.org/abs/2307.09288' },
  { era: 3, date: '2023-09', label: 'sep 2023', title: 'Mistral 7B', who: 'Mistral AI · París',
    text: 'Startup francesa, licencia Apache 2.0. Un modelo pequeño que supera a Llama 2 de 13 B.',
    why: 'Demostró que la eficiencia importa tanto como el tamaño, y que Europa también tenía un actor en la carrera.',
    tags: ['open'], src: 'https://arxiv.org/abs/2310.06825' },
  { era: 3, date: '2023-12', label: 'dic 2023', title: 'Gemini 1.0', who: 'Google DeepMind',
    text: 'Entrenado de forma nativa con texto, imagen, audio y video desde el inicio.',
    why: 'La respuesta de Google tras fusionar Brain y DeepMind. La multimodalidad dejó de ser un añadido para ser parte del entrenamiento.',
    tags: ['closed', 'multimodal'], src: 'https://arxiv.org/abs/2312.11805' },

  { era: 4, date: '2024-03', label: 'mar 2024', title: 'Claude 3', who: 'Anthropic',
    text: 'Familia Haiku · Sonnet · Opus: visión y 200 K tokens de contexto.',
    why: 'Popularizó la idea de familias por tamaño: un modelo rápido y barato, uno equilibrado y uno de máxima capacidad.',
    tags: ['closed', 'multimodal'], src: 'https://www.anthropic.com/news/claude-3-family' },
  { era: 4, date: '2024-05', label: 'may 2024', title: 'GPT-4o', who: 'OpenAI',
    text: 'Omni: voz, imagen y texto en un solo modelo; conversación por voz en tiempo real.',
    why: 'Antes, la voz pasaba por tres modelos encadenados (voz→texto→LLM→voz). Uno solo redujo la latencia y permitió captar tono y emoción.',
    tags: ['closed', 'multimodal'], src: 'https://openai.com/index/hello-gpt-4o/' },
  { era: 4, date: '2024-07', label: 'jul 2024', title: 'Llama 3.1 405B', who: 'Meta',
    text: 'El primer modelo abierto que compite de tú a tú con la frontera cerrada.',
    why: 'Por primera vez, un modelo descargable rivalizaba con GPT-4 en varios benchmarks.',
    tags: ['open'], src: 'https://arxiv.org/abs/2407.21783' },
  { era: 4, date: '2024-09', label: 'sep 2024', key: true, title: 'o1: el primer razonador', who: 'OpenAI',
    text: 'Genera una cadena de pensamiento antes de responder. Más cómputo en inferencia, mejores respuestas.',
    why: 'Abrió un segundo eje de escala: además de entrenar modelos más grandes, se puede dejar «pensar» más al modelo en cada pregunta. Matemáticas y programación dieron un salto.',
    tags: ['closed', 'reasoning'], src: 'https://openai.com/index/learning-to-reason-with-llms/' },
  { era: 4, date: '2024-12', label: 'dic 2024', title: 'DeepSeek-V3', who: 'DeepSeek · Hangzhou',
    text: 'Mezcla de expertos de 671 B (37 B activos). Entrenamiento final reportado en ~5,6 M USD de cómputo.',
    why: 'La cifra (que excluye investigación previa e infraestructura) cuestionó la idea de que solo quien gasta miles de millones puede llegar a la frontera.',
    tags: ['open'], src: 'https://arxiv.org/abs/2412.19437' },

  { era: 5, date: '2025-01-20', label: '20 ene 2025', key: true, title: 'DeepSeek-R1', who: 'DeepSeek',
    text: 'Razonador de nivel o1 con pesos abiertos (MIT). El 27 de enero Nvidia pierde ~590.000 M USD en bolsa en un día.',
    why: 'Publicó cómo entrenar un razonador con aprendizaje por refuerzo y liberó los pesos. Cuatro meses después de o1, el razonamiento ya era abierto.',
    tags: ['open', 'reasoning'], src: 'https://arxiv.org/abs/2501.12948' },
  { era: 5, date: '2025-02', label: 'feb 2025', title: 'Claude 3.7 Sonnet', who: 'Anthropic',
    text: 'Razonamiento híbrido: el mismo modelo responde rápido o «piensa» con un presupuesto que fija el usuario.',
    why: 'Convirtió el razonamiento en una perilla en lugar de un modelo aparte. Ver sección 03.',
    tags: ['closed', 'reasoning'], src: 'https://www.anthropic.com/news/claude-3-7-sonnet' },
  { era: 5, date: '2025-04', label: 'abr 2025', title: 'Qwen3', who: 'Alibaba',
    text: 'Familia abierta (Apache 2.0) con modo de pensamiento que se activa o desactiva.',
    why: 'Qwen se convirtió en la base preferida para ajustar modelos abiertos, con tamaños desde móviles hasta servidores.',
    tags: ['open', 'reasoning'], src: 'https://qwenlm.github.io/blog/qwen3/' },
  { era: 5, date: '2025-07', label: 'jul 2025', title: 'Kimi K2 · oro en la IMO', who: 'Moonshot · OpenAI · DeepMind',
    text: 'Moonshot abre un modelo de 1 billón de parámetros para agentes. Modelos de OpenAI y DeepMind logran nivel de oro en la Olimpiada de Matemáticas.',
    why: 'Dos señales del mismo mes: los modelos abiertos ya apuntaban a agentes, y los cerrados resolvían problemas de olimpiada inéditos en lenguaje natural.',
    tags: ['open'], src: 'https://moonshotai.github.io/Kimi-K2/' },
  { era: 5, date: '2025-08', label: 'ago 2025', title: 'GPT-5 y gpt-oss', who: 'OpenAI',
    text: 'GPT-5 enruta entre modo rápido y razonador. gpt-oss: los primeros pesos abiertos de OpenAI desde GPT-2.',
    why: 'Incluso el laboratorio más cerrado volvió a publicar pesos: la presión de los modelos abiertos ya era imposible de ignorar.',
    tags: ['reasoning', 'open'], src: 'https://openai.com/index/introducing-gpt-oss/' },
  { era: 5, date: '2025-11', label: 'nov 2025', title: 'Gemini 3', who: 'Google DeepMind',
    text: 'Google encabeza los rankings de preferencia al lanzarlo; la cima cambia de dueño cada pocas semanas.',
    why: 'La frontera se volvió rotativa: ningún laboratorio mantiene el primer lugar por mucho tiempo.',
    tags: ['closed', 'multimodal'], src: 'https://blog.google/products/gemini/gemini-3/' },

  { era: 6, date: '2026-04', label: 'abr 2026', title: 'DeepSeek V4', who: 'DeepSeek',
    text: 'Mezcla de expertos de 1,6 billones de parámetros, contexto de 1 M de tokens, licencia MIT.',
    why: 'Según su propia estimación, se ubica 3–6 meses detrás de la frontera cerrada. Las cifras de benchmarks son autorreportadas.',
    tags: ['open', 'reasoning'], src: 'https://rits.shanghai.nyu.edu/ai/deepseek-releases-v4-open-source-1-6t-moe-with-1m-context' },
  { era: 6, date: '2026-07', label: 'jun – sep 2026', title: 'Generación Claude 5', who: 'Anthropic',
    text: 'Fable 5, Sonnet 5, Opus 5 y Opus 5.5: modelos pensados para trabajo agéntico de larga duración.',
    why: 'El objetivo deja de ser la mejor respuesta en un turno y pasa a ser completar tareas de horas verificando su propio trabajo.',
    tags: ['closed', 'reasoning'], src: 'https://ground.news/article/introducing-claude-opus-5-anthropic' },
  { era: 6, date: '2026-09-03', label: 'sep 2026', title: 'GPT-6 Astra', who: 'OpenAI',
    text: 'Despliegue escalonado desde el 3 de septiembre; énfasis en uso del computador, software y ciberseguridad.',
    why: 'Las fechas de disponibilidad general varían según la fuente; el lanzamiento inicial fue para organizaciones seleccionadas.',
    tags: ['closed', 'reasoning'], src: 'https://news.bgov.com/artificial-intelligence/openai-rolls-out-gpt-6-astra-model-with-cyber-guardrails-1' },
];

export const PLAYERS = [
  { year: 2010, name: 'Google DeepMind', models: 'Gemini · Gemma', country: 'EE. UU. / R. U.' },
  { year: 2015, name: 'OpenAI', models: 'GPT · o-series · gpt-oss', country: 'EE. UU.' },
  { year: 2021, name: 'Anthropic', models: 'Claude', country: 'EE. UU.' },
  { year: 2023, name: 'Meta', models: 'Llama (primer LLM abierto en 2023)', country: 'EE. UU.' },
  { year: 2023, name: 'Mistral AI', models: 'Mistral · Mixtral', country: 'Francia' },
  { year: 2023, name: 'xAI', models: 'Grok', country: 'EE. UU.' },
  { year: 2023, name: 'DeepSeek', models: 'V3 · R1 · V4', country: 'China' },
  { year: 2023, name: 'Alibaba · Qwen', models: 'Qwen (abierto desde 2023)', country: 'China' },
  { year: 2023, name: 'Moonshot AI', models: 'Kimi', country: 'China' },
];

// Stanford HAI AI Index 2025, technical performance chapter.
export const GAPS = {
  arena: {
    title: 'Chatbot Arena · ventaja del líder (%)',
    before: 'ene 2024', after: 'feb 2025', max: 12,
    rows: [
      { label: 'Cerrado vs abierto', before: 8.04, after: 1.7 },
      { label: 'Top 1 vs top 10', before: 11.9, after: 5.4 },
    ],
  },
  country: {
    title: 'EE. UU. vs China · ventaja en benchmarks (puntos porcentuales)',
    before: 'fin 2023', after: 'fin 2024', max: 32,
    rows: [
      { label: 'MMLU (saber)', before: 17.5, after: 0.3 },
      { label: 'MMMU (multimodal)', before: 13.5, after: 8.1 },
      { label: 'MATH', before: 24.3, after: 1.6 },
      { label: 'HumanEval (código)', before: 31.6, after: 3.7 },
    ],
  },
};

// Illustrative logits for "El cielo es ___".
export const CANDIDATES = [
  ['azul', 4.0], ['gris', 2.6], ['despejado', 2.2], ['infinito', 1.2],
  ['inmenso', 1.0], ['oscuro', 0.8], ['rojo', 0.3], ['verde', 0.2],
];

export const EFFORT = {
  question: '¿Cuántas letras «r» hay en «ferrocarril»?',
  levels: {
    low: { tokens: 0, seconds: '~1 s', answer: '3', correct: false,
      thinking: [] },
    medium: { tokens: 60, seconds: '~4 s', answer: '3', correct: false,
      thinking: ['La palabra tiene «rr» dos veces…', 'f-e-rr-o-c-a-rr-i-l… cuento las r: 1, 2, 3.'] },
    high: { tokens: 240, seconds: '~15 s', answer: '4', correct: true,
      thinking: ['Deletreo letra por letra: f · e · r · r · o · c · a · r · r · i · l.', 'Marco cada r: posición 3, 4, 8 y 9.', 'Verifico: «ferro» aporta 2, «carril» aporta 2.', 'Total: 4.'] },
  },
};

export const CONTEXT = [
  { name: 'GPT-1', year: 2018, tokens: 512, label: '512' },
  { name: 'GPT-3', year: 2020, tokens: 2048, label: '2 K' },
  { name: 'GPT-4', year: 2023, tokens: 32768, label: '32 K' },
  { name: 'Claude 2.1', year: 2023, tokens: 200000, label: '200 K' },
  { name: 'Gemini 1.5', year: 2024, tokens: 1000000, label: '1 M' },
];

// side: 'parrot' supports the 2021 thesis; 'beyond' argues against it.
export const EVIDENCE = [
  { side: 'beyond', title: 'Othello-GPT', meta: 'Li et al. · 2023', src: 'https://arxiv.org/abs/2210.13382',
    text: 'Entrenado solo con secuencias de jugadas, el modelo forma una representación interna del tablero que se puede leer y editar.' },
  { side: 'beyond', title: 'Planifica antes de hablar', meta: 'Anthropic · 2025', src: 'https://www.anthropic.com/research/tracing-thoughts-language-model',
    text: 'La interpretabilidad muestra que Claude elige la palabra que rimará antes de escribir el verso, y encadena pasos intermedios en preguntas de varios saltos.' },
  { side: 'beyond', title: 'Matemática de olimpiada', meta: 'IMO · 2025', src: null,
    text: 'Demostraciones escritas en lenguaje natural, a nivel de medalla de oro, sobre problemas inéditos.' },
  { side: 'beyond', title: 'Razonadores', meta: '2024 →', src: 'https://openai.com/index/learning-to-reason-with-llms/',
    text: 'Más cómputo al pensar mejora las respuestas: un comportamiento difícil de explicar como simple repetición.' },
  { side: 'parrot', title: 'Alucinaciones', meta: 'persistente', src: null,
    text: 'Afirmaciones falsas con total fluidez. Disminuyen, pero no desaparecen.' },
  { side: 'parrot', title: 'La maldición de la inversión', meta: 'Berglund et al. · 2023', src: 'https://arxiv.org/abs/2309.12288',
    text: 'Aprender «A es B» no implica saber que «B es A».' },
  { side: 'parrot', title: 'Pensamiento infiel', meta: 'Anthropic · 2025', src: 'https://www.anthropic.com/research/reasoning-models-dont-say-think',
    text: 'La cadena de razonamiento visible no siempre refleja lo que de verdad determinó la respuesta.' },
  { side: 'parrot', title: 'Fragilidad fuera de distribución', meta: 'Apple · 2025', src: 'https://arxiv.org/abs/2506.06941',
    text: 'The Illusion of Thinking: el rendimiento colapsa al subir la complejidad de rompecabezas. Resultado debatido.' },
];

export const SOURCES = [
  ['Vaswani et al. (2017) Attention Is All You Need', 'https://arxiv.org/abs/1706.03762'],
  ['Kaplan et al. (2020) Scaling Laws for Neural Language Models', 'https://arxiv.org/abs/2001.08361'],
  ['Bender et al. (2021) On the Dangers of Stochastic Parrots', 'https://doi.org/10.1145/3442188.3445922'],
  ['Hoffmann et al. (2022) Training Compute-Optimal LLMs (Chinchilla)', 'https://arxiv.org/abs/2203.15556'],
  ['Li et al. (2023) Emergent World Representations', 'https://arxiv.org/abs/2210.13382'],
  ['Berglund et al. (2023) The Reversal Curse', 'https://arxiv.org/abs/2309.12288'],
  ['DeepSeek-AI (2025) DeepSeek-R1', 'https://arxiv.org/abs/2501.12948'],
  ['Anthropic (2025) Tracing the thoughts of a large language model', 'https://www.anthropic.com/research/tracing-thoughts-language-model'],
  ['Anthropic (2025) Reasoning models don\'t always say what they think', 'https://www.anthropic.com/research/reasoning-models-dont-say-think'],
  ['Shojaee et al. (2025) The Illusion of Thinking', 'https://arxiv.org/abs/2506.06941'],
  ['Stanford HAI (2025) AI Index Report', 'https://hai.stanford.edu/ai-index/2025-ai-index-report/technical-performance'],
];
